import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [userId, setUserId] = useState<String | null>(null)

  useEffect(() => {
    axios.get('http://localhost:9000')
      .then(res => {
        console.log(res.data[0].id)
        setUserId(res.data[0].id)
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{userId || 'no user id'}</p>
      </main>
    </div>
  )
}
