import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'


export default function Home() {
  const [userId, setUserId] = useState([])
  const [stationId, setStationId] = useState([])

  useEffect(() => {
    axios.get('http://localhost:9000/student')
      .then(res => {
        console.log(res.data[0].id)
        setUserId(res.data[0].id)
      })
    axios.get('http://localhost:9000/station')
        .then(res => {
          // console.log(res.data[0].ID)
          // setStationId(res.data[0].id)
          console.log(res.data)
        })
  }, [setUserId])
// function showStudent(){
//   const [studentId , getStudentId] = useState([]);
//     useEffect(()=>{    
//       axios.get('http://localhost:9000/student')
//       .then(res => {
//       console.log(res.data[0].id)
//       setUserId(res.data[0].id)
//     })

//     })
// }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* < button onclick ={userId}>{}</button> */}
         <p> Student{userId || 'no use '}</p>
        {/* <p>Station2 {stationId || 'no station id' }</p> */}
      </main>
    </div>
  )
}
